version: '3.7'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: skt123.321
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  web:
    image: orange-juices-backend
    depends_on:
      - db
    ports:
      - '4000:3000'
